// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzuTsP2peNkNu1kzGjbNGbPgoeMyxlL0I',
    appId: '1:1034699560608:ios:a193c680c15b2a0370dbc5',
    messagingSenderId: '1034699560608',
    projectId: 'matsu-gtd',
    storageBucket: 'matsu-gtd.firebasestorage.app',
    iosClientId:
        '1034699560608-ca3f8fc2ba61ivug5lutj2fnhiev5ltg.apps.googleusercontent.com',
    iosBundleId: 'com.example.matsuGtd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzuTsP2peNkNu1kzGjbNGbPgoeMyxlL0I',
    appId: '1:1034699560608:ios:c0e5c724b19afdfe70dbc5',
    messagingSenderId: '1034699560608',
    projectId: 'matsu-gtd',
    storageBucket: 'matsu-gtd.firebasestorage.app',
    iosClientId:
        '1034699560608-9p1qa82hh2oa9jas46crjca0ek2d554p.apps.googleusercontent.com',
    iosBundleId: 'studio.pine-app.matsuGtd.matsuGtd',
  );
}
