// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvR9H9sgzoJhns-F3VL_HkVEQKsPdvtc',
    appId: '1:1034699560608:web:6d0c7cf18470405970dbc5',
    messagingSenderId: '1034699560608',
    projectId: 'matsu-gtd',
    authDomain: 'matsu-gtd.firebaseapp.com',
    storageBucket: 'matsu-gtd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzuTsP2peNkNu1kzGjbNGbPgoeMyxlL0I',
    appId: '1:1034699560608:ios:51fd29b891ef483770dbc5',
    messagingSenderId: '1034699560608',
    projectId: 'matsu-gtd',
    storageBucket: 'matsu-gtd.firebasestorage.app',
    iosBundleId: 'studio.pine-app.matsuGtd.matsuGtd',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzuTsP2peNkNu1kzGjbNGbPgoeMyxlL0I',
    appId: '1:1034699560608:ios:1db2bad83e68ab9470dbc5',
    messagingSenderId: '1034699560608',
    projectId: 'matsu-gtd',
    storageBucket: 'matsu-gtd.firebasestorage.app',
    iosBundleId: 'com.example.matsuGtd.RunnerTests',
  );

}